[tool.black]
line-length = 100
target-version = ["py39", "py310", "py311"]
exclude = ["chroma_db", "uploads"]

[tool.isort]
profile = "black"
line_length = 100
skip = ["chroma_db", "uploads"]

[tool.flake8]
max-line-length = 100
extend-ignore = ["E203", "W503"]
exclude = ["chroma_db", "uploads", ".venv", "venv"]

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
disallow_untyped_defs = false
exclude = "(chroma_db|uploads|frontend)"

